spring:
  datasource:
    url: jdbc:postgresql://${app.db.host}:${app.db.port}/eprocurement_test
    username: gbk
    password: gbk
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml
  drop-first: true